version: 2.1

orbs: # will be used in the job
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-eb-cli: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build_deploy: # job name
    docker:
      - image: "cimg/base:stable" # docker container where the jobs run
    steps:
      - node/install: # install node
          node-version: "16.13.2"
      - aws-cli/setup # setup aws-cli
      - aws-eb-cli/setup # setup eb-cli
      - checkout # to get the latest code in repo
      - run:
          name: Install Client-Side Dependency Packages
          command: npm run client:install
      - run:
          name: Build Client-Side
          command: npm run client:build
      - run:
          name: Install Server-Side Dependency Packages
          command: npm run server:install
      - run:
          name: Build Server-Side
          command: npm run server:build
      - run:
          name: Deploy Client-Side Build
          command: npm run client:deploy
      - run:
          name: Deploy Server-Side Build
          command: npm run server:deploy

workflows:
  build_and_deploy:
    jobs:
      - build_deploy
